### ISSUE TITLE
Design props

### ISSUE THREAD

**Issue by NebojsaKrtolica** [stfsy/stfsy.github.io#1]
![image](https://user-images.githubusercontent.com/6503280/39244267-856842ee-4890-11e8-945e-bf12b6567f13.png)

@stfsy - mir gefällt das Design der Seite sehr, kannst du das CSS dazu teilen? :lipstick:

**Comment by NebojsaKrtolica** [comment]
:shipit:

**Comment by stfsy** [comment]
using the browsers default document and stylesheets to save bandwith 👍 so nothing to share here. head over to chromium to checkout the styles
